{"type": "end", "timestamp": "2024-12-13T18:04:01.298442", "step_id": "command-1317190179714240642.main.BotCommands", "task_id": "command-1317190179714240642.main", "result": null, "exception": {"type": "builtins.AssertionError", "args": ["start != end"], "details": "Traceback (most recent call last):\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\bot_commands.py\", line 60, in handle_command\n    await self._send_report(channel_id, content)\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\wrappers.py\", line 18, in new_func\n    return await find_historian().handle_step(func.__name__, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\historian.py\", line 565, in handle_step\n    result = await result\n             ^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\bot_commands.py\", line 116, in _send_report\n    report_string, img = self._reporter.get_report(arg_string)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\reporter.py\", line 283, in get_report\n    return feed_fancy_graph(arg_string)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\reporter.py\", line 60, in feed_fancy_graph\n    image_data = buffer.getvalue()\n                 ^^^^^^^^^^^^^^^^^\nValueError: I/O operation on closed file.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\historian.py\", line 565, in handle_step\n    result = await result\n             ^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\discord_bot.py\", line 243, in send_message\n    channel = self.get_channel(channel_id)\n              ^^^^\n  File \"_pydevd_bundle\\\\pydevd_pep_669_tracing_cython.pyx\", line 467, in _pydevd_bundle.pydevd_pep_669_tracing_cython.py_line_callback\n  File \"_pydevd_bundle\\\\pydevd_pep_669_tracing_cython.pyx\", line 461, in _pydevd_bundle.pydevd_pep_669_tracing_cython.py_line_callback\n  File \"C:\\Program Files\\JetBrains\\PyCharm 2024.3\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 1220, in do_wait_suspend\n    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)\n  File \"C:\\Program Files\\JetBrains\\PyCharm 2024.3\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 1235, in _do_wait_suspend\n    time.sleep(0.01)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\historian.py\", line 565, in handle_step\n    result = await result\n             ^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\bot_commands.py\", line 21, in __call__\n    return await self.handle_command(message)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\Documents\\Bryce\\rubber-duck\\rubber_duck\\bot_commands.py\", line 70, in handle_command\n    await self._send_message(channel_id, traceback.format_exc())\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\wrappers.py\", line 18, in new_func\n    return await find_historian().handle_step(func.__name__, func, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\historian.py\", line 617, in handle_step\n    _prune(step_id, self._history)\n  File \"C:\\Users\\rache\\miniconda3\\envs\\rubber-duck\\Lib\\site-packages\\quest\\historian.py\", line 129, in _prune\n    assert record['type'] == 'end', f'{record[\"type\"]} != end'\n           ^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError: start != end\n"}}